import { Inter } from 'next/font/google'
import Image from 'next/image'
import Head from 'next/head'
import Sidebar from '@/components/Sidebar'
import BootstrapClient from '@/components/BootstrapClient'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, pagina }) {
  return (
    <>
      <BootstrapClient></BootstrapClient>
      <Head>
      <title>{`SIPSE - ${String(pagina)}`}</title>
        <meta name='description' content='SIPSE'></meta>
      </Head>
      <div className='container'>
        <aside className="md:w-4/12 xl:w-1/4 2xl:w-1/5">
          <Sidebar></Sidebar>
        </aside>
      </div>
      <div className={inter.className}>{children}</div>
    </>
  )
}
